package co.gov.registraduria.commoncannonical.v3.schemas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6.fuse-780029-redhat-00001
  * 2021-04-11T00:40:52.757-05:00
 * Generated source version: 3.3.6.fuse-780029-redhat-00001
 *
 */
@WebServiceClient(name = "CustomersPortService",
                  wsdlLocation = "http://localhost:8080/ws/customers.wsdl",
                  targetNamespace = "http://registraduria.gov.co/commoncannonical/v3/schemas")
public class CustomersPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://registraduria.gov.co/commoncannonical/v3/schemas", "CustomersPortService");
    public final static QName CustomersPortSoap11 = new QName("http://registraduria.gov.co/commoncannonical/v3/schemas", "CustomersPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/customers.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomersPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/customers.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomersPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomersPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersPortService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11() {
        return super.getPort(CustomersPortSoap11, CustomersPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersPort
     */
    @WebEndpoint(name = "CustomersPortSoap11")
    public CustomersPort getCustomersPortSoap11(WebServiceFeature... features) {
        return super.getPort(CustomersPortSoap11, CustomersPort.class, features);
    }

}
