package co.gov.registraduria.commoncannonical.v3.schemas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6.fuse-780029-redhat-00001
 * 2021-04-11T00:40:52.694-05:00
 * Generated source version: 3.3.6.fuse-780029-redhat-00001
 *
 */
@WebService(targetNamespace = "http://registraduria.gov.co/commoncannonical/v3/schemas", name = "CustomersPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomersPort {

    @WebMethod
    @WebResult(name = "getCustomerStatusRs", targetNamespace = "http://registraduria.gov.co/commoncannonical/v3/schemas", partName = "getCustomerStatusRs")
    public GetCustomerStatusRs getCustomerStatus(
            @WebParam(partName = "getCustomerStatusRq", name = "getCustomerStatusRq", targetNamespace = "http://registraduria.gov.co/commoncannonical/v3/schemas")
                    GetCustomerStatusRq getCustomerStatusRq
    );
}
